In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import pickle as pkl

In [ ]:
comp = pkl.load(open('/home/tru_exe/projects/earthquakeDSS/data/compiled_data_class.pkl', 'rb'))
comp.head()

,tweet_id,tweet_text,label
0,'451585608612208640',Guys northem chile really needs a support mess...,sympathy_and_emotional_support
1,'451500842395250688',RT @Euphorian54: #Rehearsal time w/ @debbiegib...,not_related_or_irrelevant
2,'451833189439246336',Happy B-Day! @AllRiseSilver https://t.co/jcfCk...,not_related_or_irrelevant
3,'451330668539031552',RT @kuroab_90: My heart goes out to the victim...,sympathy_and_emotional_support
4,'451489071404040192',"Chile Earthquake: 5 Dead, Several Seriously In...",injured_or_dead_people

In [ ]:
comp['tweet_id'] = comp['tweet_id'].str.replace("'" , "").astype(int)

1- Injured or dead people---Reports of casualties and/or injured people due to the crisis

2- Missing, trapped, or found people---Reports and/or questions about missing or found people

3- Displaced people and evacuations---People who have relocated due to the crisis, even for a short time (includes evacuations)

4- Infrastructure and utilities damage---Reports of damaged buildings, roads, bridges, or utilities/services interrupted or restored

5- Donation needs or offers or volunteering services---Reports of urgent needs or donations of shelter and/or supplies such as food, water, clothing, money, medical supplies or blood; and volunteering services

6- Caution and advice---Reports of warnings issued or lifted, guidance and tips

7- Sympathy and emotional support---Prayers, thoughts, and emotional support

8- Other useful information---Other useful information that helps understand the situation

9- Not related or irrelevant---Unrelated to the situation or irrelevant

In [ ]:
severity_map = {
    "injured_or_dead_people":4,
    "missing_trapped_or_found_people":4,
    "displaced_people_and_evacuations":3,
    "infrastructure_and_utilities_damage":3,
    "donation_needs_or_offers_or_volunteering_services":2,
    "caution_and_advice":2,
    "sympathy_and_emotional_support":1,
    "other_useful_information":1,
    "not_related_or_irrelevant":0
}

comp['severity_class'] = comp['label'].map(severity_map)

In [ ]:
comp.head()

,tweet_id,tweet_text,label,severity_class
0,451585608612208640,Guys northem chile really needs a support mess...,sympathy_and_emotional_support,1
1,451500842395250688,RT @Euphorian54: #Rehearsal time w/ @debbiegib...,not_related_or_irrelevant,0
2,451833189439246336,Happy B-Day! @AllRiseSilver https://t.co/jcfCk...,not_related_or_irrelevant,0
3,451330668539031552,RT @kuroab_90: My heart goes out to the victim...,sympathy_and_emotional_support,1
4,451489071404040192,"Chile Earthquake: 5 Dead, Several Seriously In...",injured_or_dead_people,4

In [ ]:
pkl.dump(comp, open('/home/tru_exe/projects/earthquakeDSS/data/compiled_data_w_severityClass.pkl', 'wb'))

In [ ]:
comp = pkl.load(open('/home/tru_exe/projects/earthquakeDSS/data/compiled_data_w_severityClass.pkl', 'rb'))

In [ ]:
comp.head()

,tweet_id,tweet_text,label,severity_class
0,451585608612208640,Guys northem chile really needs a support mess...,sympathy_and_emotional_support,1
1,451500842395250688,RT @Euphorian54: #Rehearsal time w/ @debbiegib...,not_related_or_irrelevant,0
2,451833189439246336,Happy B-Day! @AllRiseSilver https://t.co/jcfCk...,not_related_or_irrelevant,0
3,451330668539031552,RT @kuroab_90: My heart goes out to the victim...,sympathy_and_emotional_support,1
4,451489071404040192,"Chile Earthquake: 5 Dead, Several Seriously In...",injured_or_dead_people,4

In [ ]:
import re

def clean_tweet(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)          # remove URLs
    text = re.sub(r"@\w+", "", text)             # remove mentions
    text = re.sub(r"#(\w+)", r"\1", text)        # keep hashtag text, remove #
    text = re.sub(r"rt\s+", "", text)            # remove RT prefix
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text) # remove special chars
    text = re.sub(r"\s+", " ", text).strip()
    return text
comp["clean_text"] = comp["tweet_text"].apply(clean_tweet)
comp.head()

,tweet_id,tweet_text,label,severity_class,clean_text
0,451585608612208640,Guys northem chile really needs a support mess...,sympathy_and_emotional_support,1,guys northem chile really needs a suppomessage...
1,451500842395250688,RT @Euphorian54: #Rehearsal time w/ @debbiegib...,not_related_or_irrelevant,0,rehearsal time w amp teamdeb for hitparade amp...
2,451833189439246336,Happy B-Day! @AllRiseSilver https://t.co/jcfCk...,not_related_or_irrelevant,0,happy b day happyhyukday
3,451330668539031552,RT @kuroab_90: My heart goes out to the victim...,sympathy_and_emotional_support,1,my heagoes out to the victims of the 8 2 magni...
4,451489071404040192,"Chile Earthquake: 5 Dead, Several Seriously In...",injured_or_dead_people,4,chile earthquake 5 dead several seriously injured

In [ ]:
import tensorflow as tf

In [ ]:
from gensim.models import Word2Vec
import gensim
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk
import warnings

In [ ]:
from gensim.models import KeyedVectors

# Path to your downloaded CrisisNLP .bin file
CRISIS_BIN_PATH = "/home/tru_exe/projects/earthquakeDSS/data/crisisNLP_word2vec_model/crisisNLP_word_vector.bin"   
print("Loading CrisisNLP embeddings...")
crisis_wv = KeyedVectors.load_word2vec_format(CRISIS_BIN_PATH, binary=True)

EMBED_DIM = crisis_wv.vector_size  
print(f"Loaded {len(crisis_wv)} vectors | Dimension: {EMBED_DIM}")

Loading CrisisNLP embeddings...
Loaded 2152854 vectors | Dimension: 300

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

MAX_VOCAB = 60000
MAX_LEN   = 100

tokenizer = Tokenizer(num_words=MAX_VOCAB, oov_token="<OOV>")
tokenizer.fit_on_texts(comp["clean_text"])

word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(comp["clean_text"])
X = pad_sequences(sequences, maxlen=MAX_LEN, padding="post", truncating="post")
y = comp["severity_class"].values

In [ ]:
pkl.dump((X, y), open('/home/tru_exe/projects/earthquakeDSS/data/X_y_sequences.pkl', 'wb'))

In [18]:
X[10]

array([ 201,   12,  812,    4, 1061,    7,    2,   35,   44, 1629,    7,
        102, 1063,   12,   45,  129,   29,   53,   79,    3,    6,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0], dtype=int32)

In [19]:
print(word_index)
print(X)

{'<OOV>': 1, 'chile': 2, 'earthquake': 3, 'the': 4, 'in': 5, 'tsunami': 6, 'of': 7, '8': 8, 'prayforchile': 9, 'a': 10, 'to': 11, 'and': 12, '2': 13, 'for': 14, 's': 15, 'magnitude': 16, 'i': 17, 'after': 18, 'you': 19, 'quake': 20, 'coast': 21, 'is': 22, 'off': 23, '7': 24, 'on': 25, 'my': 26, 'are': 27, 'from': 28, 'all': 29, 'at': 30, 'northern': 31, 'that': 32, 'by': 33, 'warning': 34, 'with': 35, 'people': 36, 'iquique': 37, '6': 38, 'amp': 39, '4': 40, '5': 41, 'hit': 42, '3': 43, 'an': 44, 'prayers': 45, 'this': 46, 'news': 47, 'we': 48, 'chileearthquake': 49, 'it': 50, 'massive': 51, 'peru': 52, 'be': 53, 'just': 54, 'm': 55, 'please': 56, 'pray': 57, 'as': 58, 'was': 59, 't': 60, 'has': 61, 'powerful': 62, 'so': 63, 'now': 64, 'there': 65, 'god': 66, 'strikes': 67, '2014': 68, 'hits': 69, 'out': 70, 'me': 71, 'aftershock': 72, '0': 73, '1': 74, 'have': 75, 'following': 76, 'hope': 77, 'not': 78, 'safe': 79, 'breaking': 80, 'our': 81, 'about': 82, 'dead': 83, 'another': 84, 'chilean': 85, 'what': 86, 'everyone': 87, 'via': 88, 'struck': 89, 'strong': 90, 'affected': 91, 'but': 92, 'no': 93, 'thoughts': 94, 'us': 95, 'more': 96, 'let': 97, 'pacific': 98, 'time': 99, 'world': 100, 'warnings': 101, 'love': 102, 'who': 103, 'them': 104, 'u': 105, 'damage': 106, 'will': 107, 'video': 108, 'april': 109, 'your': 110, 'today': 111, 'one': 112, 'been': 113, 'those': 114, 'here': 115, 'can': 116, 'stay': 117, 'country': 118, 'day': 119, 'watch': 120, 'they': 121, 'earthquakes': 122, 'apr': 123, 'update': 124, 're': 125, 'near': 126, 'do': 127, 'w': 128, 'may': 129, 'new': 130, 'hawaii': 131, 'says': 132, 'tarapaca': 133, 'north': 134, 'last': 135, 'go': 136, 'don': 137, 'aftershocks': 138, 'issued': 139, 'ago': 140, 'night': 141, 'if': 142, 'japan': 143, 'follow': 144, 'good': 145, 'prayforsouthkorea': 146, 'or': 147, 'reported': 148, 'how': 149, 'keep': 150, 'major': 151, 'much': 152, 'praying': 153, '10': 154, 'were': 155, 'up': 156, 'their': 157, 'big': 158, 'offshore': 159, 'say': 160, 'waves': 161, 'yesterday': 162, 'prayforsinabung': 163, 'utc': 164, 'live': 165, '300': 166, 'lt': 167, '04': 168, 'know': 169, 'evacuation': 170, 'prayforindonesia': 171, 'over': 172, 'again': 173, 'help': 174, 'when': 175, 'than': 176, 'usgs': 177, 'depth': 178, 'ok': 179, 'thanks': 180, 'like': 181, 'areas': 182, 'reports': 183, 'triggers': 184, '20': 185, 'prayfornigeria': 186, '03': 187, 'some': 188, 'rocks': 189, 'really': 190, 'its': 191, 'need': 192, 'south': 193, 'disaster': 194, 'effect': 195, 'animation': 196, 'advisory': 197, 'travel': 198, 'going': 199, 'least': 200, 'sending': 201, 'threat': 202, 'ecuador': 203, 'times': 204, 'latest': 205, 'coastal': 206, 'thank': 207, 'okay': 208, '9': 209, 'could': 210, 'kills': 211, 'five': 212, 'santiago': 213, 'region': 214, 'de': 215, 'fuerzachile': 216, 'emergency': 217, 'gt': 218, 'evacuated': 219, 'alert': 220, 'lives': 221, 'way': 222, 'guys': 223, 'epicenter': 224, 'family': 225, 'still': 226, 'california': 227, 'killed': 228, 'see': 229, 'residents': 230, 'get': 231, 'shows': 232, 'morning': 233, 'right': 234, 'little': 235, 'tuesday': 236, 'moment': 237, 'had': 238, 'six': 239, 'second': 240, 'two': 241, 'mag': 242, 'friends': 243, 'prayer': 244, 'huge': 245, 'too': 246, 'panama': 247, 'map': 248, 'authorities': 249, 'take': 250, 'due': 251, 'president': 252, 'en': 253, 'll': 254, 'very': 255, 'area': 256, 'better': 257, 'deaths': 258, 'prisoners': 259, 'america': 260, 'always': 261, 'tonight': 262, 'happened': 263, 'death': 264, 'evacuations': 265, 'wnw': 266, 'bless': 267, 'being': 268, 'large': 269, 'back': 270, 'through': 271, 'caused': 272, 'oh': 273, 'same': 274, 'arica': 275, 'save': 276, '05': 277, 'want': 278, 'best': 279, 'terremoto': 280, 'o': 281, 'would': 282, 'even': 283, 'happy': 284, 'n': 285, 'countries': 286, '11': 287, 'escaped': 288, 'km': 289, 'down': 290, 'bad': 291, 'expected': 292, 'copper': 293, 'omg': 294, 'prison': 295, 'antofagasta': 296, 'why': 297, 'y': 298, 'rocked': 299, 'coastline': 300, 'toll': 301, 'week': 302, 'lost': 303, 'families': 304, 'hours': 305, 'others': 306, 'small': 307, 'injured': 308, 'home': 309, '02': 310, 'fuerzanortedechile': 311, 'la': 312, 'make': 313, 'along': 314, 'sparks': 315, 'many': 316, 'under': 317, 'only': 318, 'c': 319, 'center': 320, 'im': 321, 'sad': 322, 'prayformh370': 323, 'am': 324, 'happen': 325, 'energy': 326, 'deadly': 327, 'aftermath': 328, 'preliminary': 329, 'since': 330, 'ht': 331, '00': 332, 'm8': 333, 'cancelled': 334, 'earth': 335, 'life': 336, 'got': 337, 'building': 338, 'order': 339, 'victims': 340, 'he': 341, 'chilequake': 342, 'wow': 343, 'argentina': 344, 'women': 345, 'sismo': 346, 'officials': 347, 'during': 348, 'yet': 349, 'local': 350, 'believe': 351, 'wave': 352, 'bachelet': 353, '15': 354, 'three': 355, '43': 356, 've': 357, 'also': 358, 'minister': 359, 'seriously': 360, 'lifted': 361, 'mt': 362, 'his': 363, 'aleafter': 364, 'triggering': 365, 'measuring': 366, 'amazing': 367, 'm7': 368, 'while': 369, 'ocean': 370, 'evacuate': 371, 'thousands': 372, 'well': 373, 'things': 374, 'updates': 375, 'assesses': 376, 'ppl': 377, 'around': 378, 'never': 379, 'where': 380, 'entire': 381, 'hear': 382, 'close': 383, 'other': 384, 'then': 385, 'coming': 386, 'confirmed': 387, 'trending': 388, 'something': 389, '2010': 390, 'days': 391, 'sw': 392, '24': 393, 'interior': 394, 'quakes': 395, 'did': 396, 'most': 397, 'she': 398, '14': 399, 'continues': 400, 'west': 401, 'usa': 402, 'tweet': 403, 'wednesday': 404, 'killing': 405, 'lot': 406, 'every': 407, 'female': 408, 'h': 409, 'date': 410, 'look': 411, 'any': 412, 'doing': 413, 'must': 414, 'colombia': 415, 'post': 416, 'homes': 417, 'terremotoenchile': 418, 'earthquakechile': 419, 'stop': 420, 'declared': 421, 'because': 422, 'next': 423, 'office': 424, 'happening': 425, 'everything': 426, 'gonna': 427, 'government': 428, 'lima': 429, 'michelle': 430, 'wsw': 431, 'inmates': 432, 'bc': 433, 'chili': 434, 'prompts': 435, 'think': 436, 'story': 437, 'felt': 438, 'hi': 439, 'these': 440, 'use': 441, 'past': 442, 'thursday': 443, 'lord': 444, 'southern': 445, 'prayforukraine': 446, 'strict': 447, '46': 448, 'indonesia': 449, 'latin': 450, 'needs': 451, 'b': 452, 'heagoes': 453, 'tv': 454, 'show': 455, 'scale': 456, 'man': 457, 'into': 458, 'come': 459, 'alefor': 460, 'destruction': 461, 'heard': 462, 'send': 463, 'twitter': 464, 'info': 465, '33': 466, 'risk': 467, 'street': 468, 'beautiful': 469, 'situation': 470, 'fine': 471, 'getting': 472, 'issues': 473, 'alright': 474, 'city': 475, 'escape': 476, 'check': 477, 'place': 478, 'm5': 479, '44': 480, 'x': 481, 'expecting': 482, 'should': 483, 'navy': 484, 'occurred': 485, 'landslides': 486, 'state': 487, 'minutes': 488, 'top': 489, 'fuck': 490, 'high': 491, 'hoping': 492, 'adidas': 493, 'rt': 494, 'recent': 495, 'r': 496, 'crazy': 497, 'far': 498, 'fire': 499, 'yeah': 500, 'hot': 501, 'noaa': 502, '70': 503, '000': 504, 'photo': 505, 'shakes': 506, 'few': 507, 'el': 508, 'except': 509, 'goes': 510, 'richter': 511, 'event': 512, 'police': 513, 'eq': 514, 'p': 515, 'years': 516, 'watches': 517, 'costa': 518, 'away': 519, 'higher': 520, 'didn': 521, 'generated': 522, 'almost': 523, 'him': 524, 'lets': 525, 'terrifying': 526, 'american': 527, 'scared': 528, 'evacuating': 529, 'care': 530, 'd': 531, 'hour': 532, 'children': 533, 'main': 534, 'ale': 535, 'weeks': 536, 'tremor': 537, 'ripfloyd': 538, 'which': 539, 'con': 540, 'thinking': 541, 'worried': 542, 'damn': 543, 'declares': 544, 'force': 545, 'possible': 546, 'imagine': 547, 'eat': 548, 'remember': 549, 'worse': 550, 'sorry': 551, 'paof': 552, 'break': 553, 'taking': 554, 'less': 555, 'code': 556, 'l': 557, 'her': 558, 'prayfortheworld': 559, 'across': 560, 'upgraded': 561, 'eyes': 562, '40km': 563, 'safety': 564, 'shit': 565, 'ptwc': 566, 'lifts': 567, 'shock': 568, 'cnn': 569, 'forecast': 570, 'give': 571, 'nature': 572, 'prayforflores': 573, 'died': 574, 'thing': 575, 'm6': 576, 'codes': 577, 'danger': 578, '30': 579, 'leaves': 580, '01': 581, 'min': 582, 'reach': 583, 'updated': 584, 'several': 585, 'fires': 586, 'miles': 587, 'bbc': 588, 'already': 589, 'tweets': 590, 'baby': 591, 'poor': 592, '60': 593, 'actually': 594, 'canceled': 595, 'rica': 596, 'sleep': 597, 'scary': 598, 'gets': 599, 'soon': 600, 'followers': 601, '2m': 602, 'makes': 603, 'flee': 604, 'pretty': 605, 'mh370': 606, 'said': 607, 'someone': 608, 'te': 609, 'worry': 610, 'ready': 611, 'birthday': 612, 'ones': 613, 'took': 614, 'left': 615, 'making': 616, 'yes': 617, '51': 618, '40': 619, 'nicaragua': 620, '22': 621, 'causing': 622, 'return': 623, 'hard': 624, 'shore': 625, 'hey': 626, 'upgrades': 627, '08': 628, 'rip': 629, 'un': 630, 'national': 631, 'arrival': 632, 'roads': 633, 'water': 634, '13': 635, 'chileearthquakeandtsunami': 636, 'end': 637, 'sea': 638, 'com': 639, 'science': 640, 'feel': 641, 'saved': 642, 'read': 643, 'estimated': 644, 'fools': 645, 'sister': 646, 'destructive': 647, 'prices': 648, 'recently': 649, 'fucking': 650, 'wide': 651, 'casualties': 652, 'call': 653, 'having': 654, 'preparedness': 655, 'cancels': 656, '2nd': 657, 'reuters': 658, 'photos': 659, 'nearly': 660, 'wake': 661, 'impact': 662, 'wish': 663, 'special': 664, 'loved': 665, 'bigger': 666, 'devastating': 667, 'strength': 668, 'great': 669, 'allah': 670, '06': 671, 'music': 672, 'htt': 673, 'ml': 674, 'feet': 675, 'zone': 676, 'san': 677, 'seismic': 678, 'details': 679, '10km': 680, 'protect': 681, 'donate': 682, 'mis': 683, 'tsunamis': 684, 'faith': 685, 'find': 686, 'brazil': 687, 'v': 688, '16': 689, 'probably': 690, 'fault': 691, 'inside': 692, 'que': 693, 'southamerica': 694, 'might': 695, 'originals': 696, 'open': 697, '1st': 698, 'power': 699, 'los': 700, 'activity': 701, 'raw': 702, 'sure': 703, 'panic': 704, 'orders': 705, 'minor': 706, 'justin': 707, 'late': 708, 'house': 709, 'wait': 710, 'die': 711, 'tell': 712, 'seismologists': 713, 'talk': 714, 'saw': 715, 'hrs': 716, 'godbless': 717, 'immediately': 718, 'learning': 719, 'friend': 720, 'caught': 721, 'passed': 722, 'initial': 723, 'involved': 724, 'camera': 725, 'del': 726, 'buy': 727, 'fans': 728, 'gmt': 729, 'does': 730, 'suffering': 731, 'holy': 732, 'calm': 733, 'learn': 734, 'demi': 735, 'cautious': 736, 'ac360': 737, 'wasn': 738, 'liked': 739, 'whole': 740, 'men': 741, 'pain': 742, 'seem': 743, 'respond': 744, 'nw': 745, '25': 746, 'northwest': 747, 'southwest': 748, '57': 749, 'effected': 750, '58': 751, 'rattles': 752, 'slip': 753, 'military': 754, 'whatever': 755, 'forget': 756, 'cost': 757, '23': 758, 'mexico': 759, 'animals': 760, 'remains': 761, 'tomorrow': 762, 'isn': 763, 'related': 764, 'likely': 765, 'model': 766, 'behind': 767, 'triggered': 768, 'israel': 769, 'bolivia': 770, 'foot': 771, 'using': 772, 'free': 773, 'relief': 774, 'mmm': 775, 'land': 776, 'million': 777, '09': 778, '07': 779, 'experts': 780, 'vision': 781, 'such': 782, 'linda': 783, 'perry': 784, 'baylor': 785, 'shake': 786, 'minute': 787, 'real': 788, 'low': 789, 'alerts': 790, 'leave': 791, 'sirens': 792, 'wa': 793, 'room': 794, 'shaking': 795, 'level': 796, 'forces': 797, 'caltech': 798, 'mi': 799, 'cant': 800, 'year': 801, 'wanna': 802, 'sleeping': 803, 'image': 804, 'offer': 805, 'sun': 806, 'stronger': 807, 'earlier': 808, 'nothing': 809, 'british': 810, 'mb': 811, 'surrounding': 812, '4m': 813, 'deep': 814, 'looks': 815, 'welcome': 816, 'hopefully': 817, 'para': 818, 'th': 819, 'stand': 820, 'movie': 821, 'survey': 822, 'though': 823, 'sky': 824, 'valparaiso': 825, 'social': 826, 'work': 827, 'knowing': 828, 'heaand': 829, 'blog': 830, 'rescue': 831, '100': 832, 'jacket': 833, 'meet': 834, 'list': 835, 'girls': 836, 'reminder': 837, 'showing': 838, 'mine': 839, 'riot': 840, 'looting': 841, 'ignore': 842, 'glad': 843, 'bali': 844, 'face': 845, 'maybe': 846, 'word': 847, 'dont': 848, 'prepared': 849, 'chi': 850, 'mom': 851, 'seems': 852, 'observatories': 853, 'shocks': 854, 'pls': 855, 'first': 856, 'reaches': 857, 'experienced': 858, 'dyfi': 859, 'ap': 860, 'throughout': 861, 'stays': 862, 'prayforchi': 863, 'set': 864, 'tremors': 865, 'height': 866, 'buildings': 867, 'boats': 868, 'afp': 869, 'chileans': 870, 'seen': 871, 'comes': 872, 'horrible': 873, 'hair': 874, 'black': 875, 'team': 876, 'reality': 877, 'm4': 878, 'efforts': 879, 'heais': 880, 'xo': 881, 'anyone': 882, 'ask': 883, 'magnitu': 884, 'videos': 885, 'awful': 886, 'released': 887, 'centre': 888, 'hug': 889, 'told': 890, 'prepare': 891, 'potential': 892, 'widespread': 893, 'posted': 894, 'england': 895, 'ff': 896, 'se': 897, 'crap': 898, 'loves': 899, 'latestnews': 900, 'isopp': 901, 'nice': 902, 'fuerza': 903, 'natural': 904, 'accept': 905, 'restaurant': 906, 'topic': 907, 'living': 908, 'damaged': 909, 'warn': 910, 'response': 911, 'sweet': 912, 'impacted': 913, 'grow': 914, '123inkjets': 915, 'tech123': 916, 'recorded': 917, 'kilometers': 918, 'agency': 919, 'gloria': 920, 'vanderbilt': 921, 'kaley': 922, 'cuoco': 923, 'stars': 924, 'key': 925, 'images': 926, 'found': 927, 'follows': 928, 'hearts': 929, 'philippines': 930, 'official': 931, 'spread': 932, 'shinee': 933, 'ray': 934, 'abc': 935, 'wishes': 936, 'confirms': 937, 'believed': 938, 'jail': 939, 'e': 940, '77km': 941, '45': 942, 'kill': 943, 'point': 944, 'prayforch': 945, 'alein': 946, 'disasters': 947, 'lately': 948, 'failedapps': 949, 'monster': 950, '26': 951, 'sparking': 952, 'cities': 953, 'interesting': 954, 'russia': 955, 'missing': 956, 'broken': 957, 'ground': 958, 'john': 959, 'overnight': 960, 'different': 961, 'continue': 962, 'worst': 963, 'forced': 964, 'losses': 965, 'insurance': 966, 'result': 967, 'evacua': 968, 'shallow': 969, 'idol': 970, '900': 971, 'hst': 972, 'without': 973, 'shaken': 974, 'tiger': 975, 'tech': 976, 'join': 977, 'message': 978, 'university': 979, 'dark': 980, 'normal': 981, 'fb': 982, 'weather': 983, 'wall': 984, 'feeling': 985, 'mega': 986, 'jesus': 987, 'occurring': 988, 'calamity': 989, 'iwate': 990, 'laugh': 991, 'threatens': 992, 'chille': 993, '17': 994, '56': 995, 'chilenos': 996, 'rises': 997, 'terrible': 998, '21': 999, 'joke': 1000, 'allin': 1001, 'incredible': 1002, 'concerns': 1003, 'edt': 1004, 'added': 1005, 'repeat': 1006, 'registered': 1007, 'thought': 1008, 'serious': 1009, 'plz': 1010, 'before': 1011, 'followme': 1012, 'sends': 1013, 'ordered': 1014, 'put': 1015, 'reportedly': 1016, 'report': 1017, 'risks': 1018, 'giant': 1019, 'embassy': 1020, 'scientists': 1021, 'regions': 1022, 'advice': 1023, '33km': 1024, 'trend': 1025, 'hello': 1026, 'largest': 1027, '12': 1028, '28': 1029, 'amo': 1030, 'ft': 1031, 'shame': 1032, 'daily': 1033, 'information': 1034, 'goodnight': 1035, 'keeps': 1036, 'pm': 1037, 'yo': 1038, 'prayforc': 1039, 'means': 1040, 'long': 1041, 'newsofindia': 1042, 'xx': 1043, 'asking': 1044, 'brandysolamente': 1045, 'watching': 1046, 'everywhere': 1047, 'coffee': 1048, 'waiting': 1049, 'sickcunts': 1050, 'happens': 1051, 'temblor': 1052, 'cause': 1053, 'dog': 1054, '74km': 1055, 'track': 1056, 'green': 1057, 'heart': 1058, 'gma': 1059, 'youtube': 1060, 'beings': 1061, 'rise': 1062, 'light': 1063, 'significant': 1064, 'dropped': 1065, '9news': 1066, 'huh': 1067, 'written': 1068, 'charity': 1069, 'kids': 1070, 'worries': 1071, 'valpo': 1072, 'laundry': 1073, 'oraciones': 1074, 'pueblo': 1075, 'produced': 1076, 'hitting': 1077, 'uh': 1078, 'xd': 1079, 'skyfall': 1080, 'run': 1081, 'icon': 1082, 'header': 1083, 'geological': 1084, 'sushi': 1085, 'apartment': 1086, 'number': 1087, 'idea': 1088, 'went': 1089, '32': 1090, 'nor': 1091, 'f': 1092, 'terrified': 1093, 'hang': 1094, 'developing': 1095, 'fr': 1096, 'cl': 1097, 'washington': 1098, 'miners': 1099, '74': 1100, '5th': 1101, 'saturday': 1102, '2pm': 1103, 'visit': 1104, 'enlawded': 1105, 'propagation': 1106, 'restored': 1107, 'miss': 1108, 'boost': 1109, 'follobackinstantly': 1110, 'boys': 1111, 'rippling': 1112, 'por': 1113, 'angeles': 1114, 'vancouver': 1115, 'investment': 1116, 'rain': 1117, 'sat': 1118, 'climate': 1119, 'amateur': 1120, 'chaotic': 1121, 'faces': 1122, 'pocity': 1123, 'deployed': 1124, 'ur': 1125, 'beliebers': 1126, 'ily': 1127, 'kid': 1128, 'gm': 1129, 'understand': 1130, 'helping': 1131, 'sense': 1132, 'footage': 1133, 'shopping': 1134, 'white': 1135, 'peruvian': 1136, 'beaches': 1137, 'plane': 1138, 'advantage': 1139, 'relatively': 1140, 'folks': 1141, 'silent': 1142, 'spurs': 1143, 'flakoprettyx7': 1144, 'caldo': 1145, 'food': 1146, 'ssw': 1147, 'unete': 1148, 'le': 1149, 'ustedes': 1150, 'aus': 1151, 'yesterdays': 1152, 'expect': 1153, 'red': 1154, 'maximum': 1155, 'cracked': 1156, 'washed': 1157, 'cile': 1158, 'ov': 1159, 'coasts': 1160, 'hazard': 1161, 'persons': 1162, 'tweeting': 1163, 'plan': 1164, 'round': 1165, 'continuing': 1166, 'lots': 1167, 'fascinating': 1168, 'americans': 1169, 'parinacota': 1170, 'tarapac': 1171, 'flt': 1172, '370': 1173, 'streaming': 1174, 'stuck': 1175, 'zones': 1176, 'backpack': 1177, 'car': 1178, 'mar': 1179, 'locked': 1180, 'gone': 1181, 'cagetheelephant': 1182, 'health': 1183, '90': 1184, '48': 1185, '36': 1186, 'increase': 1187, 'takes': 1188, 'trigger': 1189, 'cali': 1190, 'won': 1191, 'until': 1192, 'true': 1193, '1982': 1194, 'announcement': 1195, 'parts': 1196, 'lm': 1197, 'norte': 1198, 'tune': 1199, '6am': 1200, 'et': 1201, 'newday': 1202, 'seekingalpha': 1203, 'prone': 1204, 'tony': 1205, 'injuries': 1206, 'governor': 1207, 'tras': 1208, 'example': 1209, 'woman': 1210, 'unite': 1211, 'bit': 1212, 'london': 1213, 'geologists': 1214, 'tragic': 1215, 'knows': 1216, 'recovery': 1217, 'cena': 1218, 'used': 1219, 'group': 1220, '1m': 1221, 'ando': 1222, 'economy': 1223, 'extreme': 1224, 'calif': 1225, 'netflix': 1226, 'pranks': 1227, 'dancing': 1228, 'rest': 1229, '500': 1230, 'thankfully': 1231, 'insane': 1232, 'camino': 1233, 'immediate': 1234, 'wth': 1235, 'total': 1236, 'bro': 1237, '47km': 1238, '20m': 1239, 'ports': 1240, 'jumped': 1241, 'terremotochile': 1242, 'electricity': 1243, 'responds': 1244, 'pictures': 1245, 'efe': 1246, 'amen': 1247, 'allowed': 1248, 'streets': 1249, 'network': 1250, 'activated': 1251, 'gotta': 1252, 'crustal': 1253, 'plates': 1254, 'located': 1255, 'peace': 1256, 'wtf': 1257, 'megaquake': 1258, 'grief': 1259, 'govt': 1260, 'evening': 1261, 'horns': 1262, 'photography': 1263, 'extend': 1264, 'condolences': 1265, 'included': 1266, 'g': 1267, 'todo': 1268, 'voice': 1269, '50km': 1270, 'series': 1271, 'months': 1272, 'yellowstone': 1273, 'within': 1274, 'couple': 1275, 'regarding': 1276, 'prayed': 1277, 'yep': 1278, 'above': 1279, 'pic': 1280, 'shes': 1281, 'lead': 1282, 'keeping': 1283, 'dying': 1284, 'given': 1285, 'risen': 1286, 'larger': 1287, 'await': 1288, 'ban': 1289, 'sunglasses': 1290, 'beats': 1291, 'fashion': 1292, 'among': 1293, 'preventive': 1294, 'measures': 1295, 'strongest': 1296, 'measured': 1297, 'latino': 1298, 'weird': 1299, 'miley': 1300, 'cyrus': 1301, 'afte': 1302, 'thats': 1303, 'damages': 1304, 'concentrated': 1305, 'person': 1306, 'final': 1307, 'between': 1308, 'volcano': 1309, 'venezuela': 1310, 'month': 1311, 'try': 1312, 'brothers': 1313, '2011': 1314, 'partially': 1315, 'blocking': 1316, 'highways': 1317, 'k': 1318, 'loss': 1319, 'fitch': 1320, 'unlikely': 1321, 'ratings': 1322, 'tcot': 1323, 'instagram': 1324, 'instalike': 1325, '95km': 1326, 'bieber': 1327, 'wed': 1328, 'director': 1329, 'precautionary': 1330, 'causes': 1331, 'evaluating': 1332, 'possibility': 1333, 'hundreds': 1334, 'location': 1335, 'missed': 1336, 'communities': 1337, 'came': 1338, 'fun': 1339, 'prayforforthood': 1340, 'outside': 1341, 'woods': 1342, 'league': 1343, 'wildfires': 1344, 'thousand': 1345, 'girl': 1346, 'sent': 1347, 'paul': 1348, 'summary': 1349, 'prayforperu': 1350, 'rodrigo': 1351, 'beg': 1352, 'citizens': 1353, 'prayingforchile': 1354, 'remarkably': 1355, '52': 1356, 'cst': 1357, 'sqm': 1358, 'mark': 1359, 'effective': 1360, 'regional': 1361, 'style': 1362, 'act': 1363, 'sup

In [23]:
vocab_size = min(MAX_VOCAB, len(word_index)) + 1
embedding_matrix = np.zeros((vocab_size, EMBED_DIM), dtype="float32")

hits, misses = 0, 0
for word, idx in word_index.items():
    if idx >= vocab_size:
        continue
    if word in crisis_wv:
        embedding_matrix[idx] = crisis_wv[word]
        hits += 1
    else:
        # Random init with same scale as Word2Vec vectors
        embedding_matrix[idx] = np.random.uniform(-0.25, 0.25, EMBED_DIM)
        misses += 1
        
print(f"Vocab coverage — Hits: {hits} | OOV: {misses} ({misses/(hits+misses)*100:.1f}%)")
print(f"Embedding matrix: {embedding_matrix.shape}")

Vocab coverage — Hits: 3517 | OOV: 670 (16.0%)
Embedding matrix: (4188, 300)

In [24]:
embedding_matrix[:10]  # Show first 5 vectors (including OOV token)

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.04093697,  0.09200399,  0.01902585, ...,  0.221283  ,
         0.05872974, -0.01734496],
       [ 0.343046  , -0.274161  , -0.155809  , ..., -0.452724  ,
         0.380765  , -0.148149  ],
       ...,
       [ 0.23473755,  0.04530949,  0.2323674 , ...,  0.20705217,
        -0.20676133, -0.11118555],
       [ 0.10430983,  0.224283  ,  0.23448117, ..., -0.16489221,
         0.13336535,  0.08230148],
       [ 0.203444  , -0.164255  , -0.070287  , ..., -0.062831  ,
        -0.288942  , -0.184035  ]], shape=(10, 300), dtype=float32)

In [25]:
pkl.dump((embedding_matrix), open('/home/tru_exe/projects/earthquakeDSS/data/embedding_matrix.pkl', 'wb'))

In [26]:
import pickle as pkl
emb = pkl.load(open('/home/tru_exe/projects/earthquakeDSS/data/embedding_matrix.pkl', 'rb'))
emb.shape

(4188, 300)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout

In [28]:
def build_model(vocab_size, embed_dim, embedding_matrix, max_len , num_classes=5):
    
    model = Sequential([
        Embedding(
            input_dim = vocab_size,
            output_dim = embed_dim,
            weights = [embedding_matrix],
            trainable = False,
            name="embedding_layer"
        ),
        
        Bidirectional(LSTM(256, return_sequences=True) , name = "bilstm1"),
        Dropout(0.5),
        Bidirectional(LSTM(128 , return_sequences=False)),
        Dropout(0.5),
        Dense(64, activation="relu" , name="dense1"),
        Dense(num_classes, activation="softmax" , name="output")        
    ])
    
    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    return model

In [ ]:
import tensorflow as tf

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
GPU devices: []

ValueError: No matching devices found for 'GPU:0'

In [32]:

print("All devices:", tf.config.list_physical_devices())

All devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
model = build_model(vocab_size = vocab_size, embed_dim = EMBED_DIM, embedding_matrix = embedding_matrix, max_len = MAX_LEN , num_classes=5)
model.summary()

NameError: name 'vocab_size' is not defined

In [24]:
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

/home/tru_exe/projects/earthquakeDSS/ml/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [26]:
tokenizer = AutoTokenizer.from_pretrained(
    "distilbert/distilbert-base-uncased",
)

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert/distilbert-base-uncased",
    num_labels=4,
    problem_type="multi_label_classification"
    
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1610.07it/s]
DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.